---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi-image.warm-metal.tech
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral