---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-image-warm-metal
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-image-warm-metal
subjects:
  - kind: ServiceAccount
    name: csi-image-warm-metal
    namespace: kube-system