---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-image.warm-metal.tech
  labels:
    {{- include "warm-metal-csi-driver.labels" . | nindent 4 }}
provisioner: csi-image.warm-metal.tech