name: cri-o-10mins
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start a kind cluster with crio
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-${{ github.run_id }}
          kubectl_version: 'v1.25.2'
          node_image: 'docker.io/warmmetal/kindest-node-crio:v1.25.2-csi-driver-image'
      - name: Install private registry
        run: ./hack/ci/setup_private_registry.sh
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Install the CSI Driver
        run: ./hack/ci/install_driver.sh
      - name: Run integration Tests
        run: ./hack/ci/test.sh
      - name: Uninstall the CSI Driver
        run: ./hack/ci/uninstall_driver.sh