name: cri-o
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up minikube
        uses: opsgang/ga-setup-minikube@v0.1.2
        with:
          minikube-version: '1.20.0'
          k8s-version: '1.21.0'
      - name: Start a Kubernetes cluster with cri-o
        run: ./hack/ci/setup_crio_cluster.sh 'v1.21.0'
      - name: Build image
        run: ./hack/ci/build.sh
      - name: Install the CSI Driver
        run: ./hack/ci/install_driver_crio.sh
      - name: Run integration Tests
        run: ./hack/ci/test.sh
      - name: Uninstall the CSI Driver
        run: ./hack/ci/uninstall_driver_crio.sh