name: docker-containerd
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: ./hack/ci/build.sh
      - uses: opsgang/ga-setup-minikube@v0.1.2
        with:
          minikube-version: '1.20.0'
          k8s-version: '1.21.0'
      - name: Start a Kubernetes cluster with docker
        run: ./hack/ci/setup_docker_cluster.sh
      - name: Install the CSI Driver
        run: ./hack/ci/install_driver.sh
      - name: Run integration Tests
        run: ./hack/ci/test.sh